### ISSUE TITLE
Empty `src-block`  snippet insertted at eop of file.

### ISSUE THREAD

**Issue by c0001** [tumashu/el2org#4]
Some typo for this problem in source file, which I've create a code blame for it, please follow below link to see the blam-description:

https://github.com/tumashu/el2org/commit/4cbcdfa4ec4ebc20dd859c3fbb578d753bfa7b29#r33403715

`el2org`  was the daily using tool for me, Hope for this bug fixing.

**Comment by tumashu** [comment]
pr is welcome :-)

**Comment by c0001** [comment]
I've created the PR, sorry for non-comprehensive thoughts for this  bug, all needed thing did in the patch,
TKS.  

> PR;
> https://github.com/tumashu/el2org/pull/5#issue-275907608
