### ISSUE TITLE
Escape tilde in README.md export

### ISSUE THREAD

**Issue by mitchellroe** [tumashu/el2org#6]
It looks like, when a block is exported which contains tilde characters (i.e. `~`), they are not escaped when exporting to markdown for the README.  Unfortunately, this leads to some strange behavior within Markdown, as the tilde character is a control character, and can result in some text being displayed with a strikethrough.

See https://github.com/tumashu/gnus-select-account/blob/master/README.md for an example.

This:
```
2.  Add account information to file: "~/.authinfo.gpg" or "~/.authinfo", for example:
```

... turns into this:

2.  Add account information to file: "~/.authinfo.gpg" or "~/.authinfo", for example:

**Comment by tumashu** [comment]
I think it is ox-md bug :-)

**Comment by mitchellroe** [comment]
Ah.  Thanks.  I'll head over there.  Sorry for the noise.
